empty-blocks:
  EmptyClassBlock:
    active: false

style:
  ForbiddenComment:
    active: false
  WildcardImport:
    excludeImports:
      - 'kotlinx.coroutines.flow.*'
      - 'java.util.*'
      - 'org.junit.Assert.*'

complexity:
  TooManyFunctions:
    active: false
